[package]
name = "burnout"
version = "0.1.0"
authors = ["Benjamin Pannell <benjamin@pannell.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []

table_storage = []

[dependencies]
actix = "0.9"
actix-cors = "0.2"
actix-http = "1.0"
actix-rt = "1.0"
actix-service = "1.0"
actix-web = "2.0"
actix-web-httpauth = "0.4"
actix-web-prom = "0.2"
async-trait = "0.1.31"
azure_sdk_core = "0.43.3"
azure_sdk_storage_core = "0.43.3"
azure_sdk_storage_table = "0.40.5"
biscuit = "0.3"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.7"
futures = "0.3"
http = "0.2"
lazy_static = "1.4"
log = "0.4"
md5 = "0.7"
oidc = "0.3"
percent-encoding = "2.1"
prometheus = "0.8"
rand = "0.6"
reqwest = "0.9"
sentry = { version = "0.18", features = ["with_env_logger"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.7", features = ["serde", "v4", "u128"] }