openapi: 3.0.1
info:
  title: Burnout
  description: Burnout is a tool used to anonymously track your team's happiness and risk of burnout.
  license:
    name: MIT
    url: https://sierrasoftworks.com/licenses/MIT
  version: 1.0.
  
servers:
  - url: https://burnout.sierrasoftworks.com
  - url: http://localhost:8000
  
tags:
  - name: health
    description: APIs used to determine the health of a Burnout instance.
  - name: teams
    description: APIs used to manage and retrieve team information.
  - name: reports
    description: APIs used to manage burnout reports by individuals.

paths:
  /api/v1/health:
    get:
      tags:
        - health

      summary: Get Health (v2)
      description: Gets the current health status of the Burnout instance.
      operationId: health_v2
  /api/v1/teams:
    get:
      tags:
        - teams
      security:
        - AzureAD: [Teams.Read]

      summary: Get Teams (v1)
      description: Gets the list of teams that you have access to.
      operationId: teams_v1
    post:
      tags:
        - teams
      security:
        - AzureAD: [Teams.Write]

      summary: New Team (v1)
      description: Creates a new team on the server.
      operationId: new_team_v1
  /api/v1/team/{id}:
    get:
      tags:
        - teams
      security:
        - AzureAD: [Teams.Read]

      summary: Get Team (v1)
      description: Gets a specific team from the server based on its ID.
      operationId: team_v1
    put:
      tags:
        - teams
      security:
        - AzureAD: [Teams.Write]

      summary: Store Team (v1)
      description: Stores a team idempotently with the given identifier, replacing an existing instance if one is present.
      operationId: store_team_v1
  /api/v1/team/{teamId}/users:
    get:
      tags:
        - teams
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Get Team Role Assignments (v1)
      description: Gets the list of users which can access this team and their role assignments.
      operationId: role_assignments_v1
  /api/v1/team/{teamId}/user/{userId}:
    get:
      tags:
        - teams
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Get User Role Assignment (v1)
      description: Gets the details of a user's role assignment within a team.
      operationId: role_assignment_v1
    put:
      tags:
        - teams
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Update User Role Assignment (v1)
      description: Update the role assignment associated with a user on a given team.
      operationId: update_role_assignment_v1
    delete:
      tags:
        - teams
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Remove User Role Assignment (v1)
      description: Removes a user's role assignment from a team.
      operationId: remove_role_assignment_v1
  /api/v1/team/{teamId}/reports:
    get:
      tags:
        - teams
      security:
        - AzureAD: [Teams.Read]
      
      summary: Get Team Reports (v1)
      description: Fetches the reports submitted for a team.
      operationId: get_team_reports_v1
  /api/v1/reports:
    get:
      tags:
        - reports
      security:
        - AzureAD: [Reports.Read]
      
      summary: Get Your Reports (v1)
      description: Fetches the full history of your report submissions.
      operationId: get_reports_v1
    post:
      tags:
        - reports
      security:
        - AzureAD: [Reports.Write]
      
      summary: Submit Report (v1)
      description: Submits a new report which will appear in your report history as well as that of the teams you are a member of.
      operationId: new_report_v1
components:
  securitySchemes:
    AzureAD:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/a26571f1-22b3-4756-ac7b-39ca684fab48/oauth2/v2.0/authorize
          scopes:
            "Reports.Read": Allows the reading of your report data.
            "Reports.Write": Allows the submission of reports.
            "Teams.Read": Allows the reading of team information.
            "Teams.Write": Allows the creation, modification and removal of teams.
            "RoleAssignments.Write": Allows the creation, modification and removal of role assignments for teams.
            