---
apiVersion: v1
kind: Service
metadata:
  name: burnout-server
spec:
  selector:
    app.kubernetes.io/name: burnout
    app.kubernetes.io/instance: burnout-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP